---
integration: minitest
environment_variables:
  RAILS_ENV: test
includes:
  - test
requires:
  - ./config/environment
matcher:
  ignore:
    - SlackController#plus_params
    - SlackController#team_params
  subjects:
    - GiveUpvote
    - SlackController
