---
integration: minitest
environment_variables:
  RAILS_ENV: test
includes:
  - test
requires:
  - ./config/environment
matcher:
  subjects:
    - GiveUpvote
    - SlackController
    - InMemorySlackAdapter
    - AliasToUserTag
    - SlackAliasMessageParser
  ignore:
    - SlackController#leaderboard
