development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  connect_timeout: 5
  database: plusone_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  connect_timeout: 5
  database: plusone_test
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  connect_timeout: 5
  url: <%= ENV["DATABASE_URL"] %>
